//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMNPitchData.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitchAverage
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public string PitchType { get; set; }
        public string BatterHand { get; set; }
        public Nullable<decimal> AvgReleaseVelocity { get; set; }
        public Nullable<int> ReleaseVelocitySampleSize { get; set; }
        public Nullable<decimal> AvgSpinRate { get; set; }
        public Nullable<int> SpinRateSampleSize { get; set; }
        public Nullable<decimal> SwStrRate { get; set; }
        public Nullable<int> SwStrRateSampleSize { get; set; }
    }
}
