//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMNPitchData.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitch
    {
        public int PitchID { get; set; }
        public Nullable<int> seasonYear { get; set; }
        public string gameString { get; set; }
        public Nullable<System.DateTime> gameDate { get; set; }
        public string gameType { get; set; }
        public string visitor { get; set; }
        public string home { get; set; }
        public Nullable<int> visitingTeamFinalRuns { get; set; }
        public Nullable<int> homeTeamFinalRuns { get; set; }
        public Nullable<int> inning { get; set; }
        public string side { get; set; }
        public Nullable<int> batterId { get; set; }
        public string batter { get; set; }
        public string batterHand { get; set; }
        public Nullable<int> pitcherId { get; set; }
        public string pitcher { get; set; }
        public string pitcherHand { get; set; }
        public Nullable<int> catcherId { get; set; }
        public string catcher { get; set; }
        public Nullable<int> timesFaced { get; set; }
        public string batterPosition { get; set; }
        public Nullable<int> balls { get; set; }
        public Nullable<int> strikes { get; set; }
        public Nullable<int> outs { get; set; }
        public string manOnFirst { get; set; }
        public string manOnSecond { get; set; }
        public string manOnThird { get; set; }
        public string endManOnFirst { get; set; }
        public string endManOnSecond { get; set; }
        public string endManOnThird { get; set; }
        public Nullable<int> visitingTeamCurrentRuns { get; set; }
        public Nullable<int> homeTeamCurrentRuns { get; set; }
        public string pitchResult { get; set; }
        public string pitchType { get; set; }
        public string releaseVelocity { get; set; }
        public string spinRate { get; set; }
        public string spinDir { get; set; }
        public string px { get; set; }
        public string pz { get; set; }
        public string szt { get; set; }
        public string szb { get; set; }
        public string x0 { get; set; }
        public string y0 { get; set; }
        public string z0 { get; set; }
        public string vx0 { get; set; }
        public string vy0 { get; set; }
        public string vz0 { get; set; }
        public string ax { get; set; }
        public string ay { get; set; }
        public string az { get; set; }
        public string paResult { get; set; }
        public string runsHome { get; set; }
        public string battedBallType { get; set; }
        public string battedBallAngle { get; set; }
        public string battedBallDistance { get; set; }
        public string atbatDesc { get; set; }
    }
}
